### ISSUE TITLE
AML extension fails on ARO

### ISSUE THREAD

**Issue by ezYakaEagle442** [Azure/AML-Kubernetes#115]
I have an ARO cluster and sucessfully created an Azure Storage account with a private-endpoint, successfully tested NFS access with the Azure File CSI driver.

I then tried to install the AML extnesion following the [docs ](https://github.com/Azure/AML-Kubernetes/blob/master/docs/deploy-on-ocp.md):

```sh
az k8s-extension create --name $AML_K8S_EXTENSION_NAME --extension-type Microsoft.AzureML.Kubernetes \
openshift=True \
--cluster-name $azure_arc_aro \
--resource-group $aro_rg_name \
--configuration-settings enableTraining=True \
--cluster-type connectedClusters \
--scope cluster
``` 

it fails witrh : 
```console
unrecognized arguments: openshift=True
```

My CLI is up to date : 

```sh
az version
``` 

```console
{
  "azure-cli": "2.27.2",
  "azure-cli-core": "2.27.2",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "aks-preview": "0.5.31",
    "appservice-kube": "0.1.20",
    "azure-firewall": "0.12.0",
    "connectedk8s": "1.1.8",
    "connectedmachine": "0.4.0",
    "customlocation": "0.1.2",
    "deploy-to-azure": "0.2.0",
    "k8s-configuration": "1.1.0",
    "k8s-extension": "0.7.0",
    "spring-cloud": "2.7.1"
  }
}
```

**Comment by ezYakaEagle442** [comment]
@sauryadas

**Comment by Zhong-J** [comment]
openshift argument is under configuration-settings.
Please modify it as,
az k8s-extension create --name $AML_K8S_EXTENSION_NAME --extension-type Microsoft.AzureML.Kubernetes \
--cluster-name $azure_arc_aro \
--resource-group $aro_rg_name \
--configuration-settings enableTraining=True openshift=True \
--cluster-type connectedClusters \
--scope cluster

**Comment by ezYakaEagle442** [comment]
Indeed this fixed the issue

**Comment by ezYakaEagle442** [comment]
@Zhong-J 
but the extension looks stuck in PENDING state since a while, how to troubleshoot ?
how long is supposed to take this command ?

**Comment by Zhong-J** [comment]
Usually it takes around 10 minutes.
Is it ready now？

**Comment by ezYakaEagle442** [comment]
@Zhong-J 
No .... I have deleted the extension and tried with DEBUG option : 

az k8s-extension create --name $AML_K8S_EXTENSION_NAME --extension-type Microsoft.AzureML.Kubernetes \
--cluster-name $azure_arc_aro \
--resource-group $aro_rg_name \
--configuration-settings enableTraining=True enableInference=True openshift=True \
--cluster-type connectedClusters \
--scope cluster \
**--debug**


```console
cli.knack.cli: Command arguments: ['k8s-extension', 'create', '--name', 'amlarc-compute', '--extension-type', 'Microsoft.AzureML.Kubernetes', '--cluster-name', 'Azure-Arc-ARO', '--resource-group', 'rg-azarc-aro-francecentral', '--configuration-settings', 'enableTraining=True', 'enableInference=True', 'openshift=True', '--cluster-type', 'connectedClusters', '--scope', 'cluster', '--debug']
cli.knack.cli: __init__ debug log:
Enable color in terminal.
cli.knack.cli: Event: Cli.PreExecute []
cli.knack.cli: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f905536cbf8>, <function OutputProducer.on_global_arguments at 0x7f90552a1730>, <function CLIQuery.on_global_arguments at 0x7f90552be840>]
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableCreate []
cli.azure.cli.core: Modules found from index for 'k8s-extension': ['azext_k8s_extension']
cli.azure.cli.core: Loading command modules:
cli.azure.cli.core: Name                  Load Time    Groups  Commands
cli.azure.cli.core: Total (0)                 0.000         0         0
cli.azure.cli.core: These extensions are not installed and will be skipped: ['azext_ai_examples', 'azext_next']
cli.azure.cli.core: Loading extensions:
cli.azure.cli.core: Name                  Load Time    Groups  Commands  Directory
cli.azure.cli.core: k8s-extension             0.004         1         4  /home/pinpin/.azure/cliextensions/k8s-extension
cli.azure.cli.core: Total (1)                 0.004         1         4
cli.azure.cli.core: Loaded 1 groups, 4 commands.
cli.azure.cli.core: Found a match in the command table.
cli.azure.cli.core: Raw command  : k8s-extension create
cli.azure.cli.core: Command table: k8s-extension create
cli.knack.cli: Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7f9054d1d268>]
cli.azure.cli.core.azlogging: metadata file logging enabled - writing logs to '/home/pinpin/.azure/commands/2021-09-03.18-02-14.k8s-extension_create.18765.log'.
az_command_data_logger: command args: k8s-extension create --name {} --extension-type {} --cluster-name {} --resource-group {} --configuration-settings {} {} {} --cluster-type {} --scope {} --debug
cli.knack.cli: Event: CommandInvoker.OnPreArgumentLoad [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f9054cb1620>, <function register_global_query_examples_argument.<locals>.register_query_examples at 0x7f9054cb1730>]
cli.knack.cli: Event: CommandInvoker.OnPostArgumentLoad []
cli.knack.cli: Event: CommandInvoker.OnPostCommandTableCreate [<function register_ids_argument.<locals>.add_ids_arguments at 0x7f9054cb17b8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7f9054cb18c8>]
cli.knack.cli: Event: CommandInvoker.OnCommandTableLoaded []
cli.knack.cli: Event: CommandInvoker.OnPreParseArgs []
cli.knack.cli: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f90552a17b8>, <function CLIQuery.handle_query_parameter at 0x7f90552be8c8>, <function register_global_query_examples_argument.<locals>.handle_example_parameter at 0x7f9054cb16a8>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f9054cb1840>]
az_command_data_logger: extension name: k8s-extension
az_command_data_logger: extension version: 0.7.0
Command group 'k8s-extension' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
cli.azure.cli.core.commands.client_factory: Getting management service client client_type=SourceControlConfigurationClient
cli.azext_k8s_extension.partner_extensions.AzureMLKubernetes: The installed AzureML extension for AML inference is experimental and not covered by customer support. Please use with discretion.
cli.azure.cli.core.util: azure.cli.core.util.handle_exception is called with an exception:
cli.azure.cli.core.util: Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 231, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 657, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 720, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 691, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 328, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/pinpin/.azure/cliextensions/k8s-extension/azext_k8s_extension/custom.py", line 130, in create_k8s_extension
    config_protected_settings, configuration_settings_file, configuration_protected_settings_file)
  File "/home/pinpin/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py", line 108, in Create
    self.__validate_config(configuration_settings, configuration_protected_settings)
  File "/home/pinpin/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py", line 189, in __validate_config
    self.__validate_scoring_fe_settings(configuration_settings, configuration_protected_settings)
  File "/home/pinpin/.azure/cliextensions/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py", line 224, in __validate_scoring_fe_settings
    "Provide ssl certificate and key. "
azure.cli.core.azclierror.InvalidArgumentValueError: Provide ssl certificate and key. Otherwise explicitly allow insecure connection by specifying '--configuration-settings allowInsecureConnections=true'

cli.azure.cli.core.azclierror: Provide ssl certificate and key. Otherwise explicitly allow insecure connection by specifying '--configuration-settings allowInsecureConnections=true'
az_command_data_logger: Provide ssl certificate and key. Otherwise explicitly allow insecure connection by specifying '--configuration-settings allowInsecureConnections=true'
cli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x7f9054d1d488>]
az_command_data_logger: exit code: 1
cli.__main__: Command ran in 0.978 seconds (init: 0.193, invoke: 0.784)
telemetry.save: Save telemetry record of length 3383 in cache
telemetry.check: Negative: The /home/pinpin/.azure/telemetry.txt was modified at 2021-09-03 18:01:34.844383, which in less than 600.000000 s

```

**Comment by ezYakaEagle442** [comment]
I have found the source code at [https://github.com/Azure/azure-cli-extensions/blob/main/src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py](https://github.com/Azure/azure-cli-extensions/blob/main/src/k8s-extension/azext_k8s_extension/partner_extensions/AzureMLKubernetes.py)

may I specify that I did set as well  ****enableInference=True** :** 

az k8s-extension create --name $AML_K8S_EXTENSION_NAME --extension-type Microsoft.AzureML.Kubernetes \
--cluster-name $azure_arc_aro \
--resource-group $aro_rg_name \
--configuration-settings enableTraining=True **enableInference=True** openshift=True \
--cluster-type connectedClusters \
--scope cluster \
--debug

**Comment by Zhong-J** [comment]
@ezYakaEagle442 , there are 4 options to enable inference. You can refer to this doc https://github.com/Azure/amlarc-preview/blob/main/docs/deploy-extension.md.

The most straightforward way is option 1, that enables http endpoint. You need to add 'allowInsecureConnections=True' under configuration settings.

**Comment by Bozhong68** [comment]
@ezYakaEagle442 are you still blocked? For OCP or ARO installation, there are prerequisite steps below, please ensure all prerequisite steps are done:
https://github.com/Azure/AML-Kubernetes/blob/master/docs/deploy-on-ocp.md

**Comment by Bozhong68** [comment]
@ezYakaEagle442 we are closing the issue, please feel free to re-open if the issue still persists.
