### ISSUE TITLE
TensorFlow with ScriptRunConfig fails on loading dataset

### ISSUE THREAD

**Issue by lenisha** [Azure/AML-Kubernetes#59]
Running Distributed TF Job with `ScriptRunConfig` fails loading MNIST dataset
https://github.com/lenisha/AML-Kubernetes/blob/master/docs/sample-notebooks/001-Tensorflow/train-tensorflow-resume-training.ipynb
```
tf_env = Environment(name='tf-gpu-pandas')
# Ensure the required packages are installed (we need pandas and fus and Azure ML defaults)
packages = CondaDependencies.create(pip_packages=['azureml-core==1.20.0',
                                                  'azureml-defaults=1.20.0',
                                                  'tensorflow-gpu==2.2.0',
                                                  'azureml-dataprep[pandas,fuse]',
                                                  'azureml-dataset-runtime[fuse,pandas]'])
tf_env.python.conda_dependencies = packages
#register environment for re-use
#tf_env.register(workspace=ws)
args = ['--data-folder', dataset.as_named_input('mnist').as_mount() ]
src = ScriptRunConfig(source_directory=script_folder,
                      compute_target=compute_target,
                      arguments=args,
                      script='tf_mnist_with_checkpoint.py',                     
                      environment=tf_env)

```

error in Eval
```
[Yesterday 4:21 PM] Elena Neroslavskaya
    
Hi amlk8s-training
Trying to convert Estimator to ScriptRunConfig and run on AKS . TensorFlow notebook  https://github.com/lenisha/AML-Kubernetes/blob/master/docs/sample-notebooks/001-Tensorflow/train-tensorflow-resume-training.ipynb

tf_env = Environment(name='tf-gpu-pandas')
# Ensure the required packages are installed (we need pandas and fus and Azure ML defaults)
packages = CondaDependencies.create(pip_packages=['azureml-core==1.20.0',
                                                  'azureml-defaults=1.20.0',
                                                  'tensorflow-gpu==2.2.0',
                                                  'azureml-dataprep[pandas,fuse]',
                                                  'azureml-dataset-runtime[fuse,pandas]'])
tf_env.python.conda_dependencies = packages
#register environment for re-use
#tf_env.register(workspace=ws)
args = ['--data-folder', dataset.as_named_input('mnist').as_mount() ]
src = ScriptRunConfig(source_directory=script_folder,
                      compute_target=compute_target,
                      arguments=args,
                      script='tf_mnist_with_checkpoint.py',                     
                      environment=tf_env)

It fails on processing the mapping for dataset, would it have to be declared differently from estimator args?

Processing input mnist
2021-02-04 21:15:02 [job-akse-arc-tf-training1-1612473280-58095b4e-rmmfl, unknown_ip] NFS dataset mount failed: invalid syntax (<string>, line 1)
2021-02-04 21:15:02 [job-akse-arc-tf-training1-1612473280-58095b4e-rmmfl, unknown_ip] Traceback (most recent call last):
2021-02-04 21:15:02 [job-akse-arc-tf-training1-1612473280-58095b4e-rmmfl, unknown_ip]   File "/cmaks_mnt/workspaceblobstore/azureml/akse-arc-tf-training1_1612473280_58095b4e/azureml-setup/context_managers.py", line 315, in redirect_dataset_to_nfs
2021-02-04 21:15:02 [job-akse-arc-tf-training1-1612473280-58095b4e-rmmfl, unknown_ip]     dataset_source = eval(json.loads(repr(dataset))["source"][0])
2021-02-04 21:15:02 [job-akse-arc-tf-training1-1612473280-58095b4e-rmmfl, unknown_ip]   File "<string>", line 1
2021-02-04 21:15:02 [job-akse-arc-tf-training1-1612473280-58095b4e-rmmfl, unknown_ip]     http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
2021-02-04 21:15:02 [job-akse-arc-tf-training1-1612473280-58095b4e-rmmfl, unknown_ip]         ^
2021-02-04 21:15:02 [job-akse-arc-tf-training1-1612473280-58095b4e-rmmfl, unknown_ip] SyntaxError: invalid syntax
2021-02-04 21:15:02 [job-akse-arc-tf-training1-1612473280-58095b4e-rmmfl, unknown_ip] Initialize DatasetContextManager.


Edited​                  9 replies from you, Ada, and Adarsh . Press Enter to expand replies.                                            9 replies from you, Ada, and Adarsh               <https://teams.microsoft.com/l/message/19:8f4e5783d8534ae7bec7880627225fe4@thread.skype/1612473707055?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;groupId=88aa174e-6310-4634-bfcb-5761e1a1190a&amp;parentMessageId=1612473707055&amp;teamName=ML Platform&amp;channelName=amlk8s-training&amp;createdTime=1612473707055>
```

**Comment by Bozhong68** [comment]
closing staled issue
